/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream a cited answer to the question over SSE: steps, sources, tokens, done with the
         *     thread and request ids; or error. A repeated first question replays sources, the answer
         *     and done.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{request_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Vote On Answer
         * @description Record the reader's vote on the answer the request gave, the one its done frame named,
         *     in place of any earlier vote; a null vote takes it back.
         */
        put: operations["vote_on_answer_chat__request_id__vote_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatErrorCode
         * @description The names chat reports its own refusals under, beside core's ErrorCode.
         * @enum {string}
         */
        ChatErrorCode: "SpendCapReachedError" | "ThreadFullError";
        /**
         * ChatErrorResponse
         * @description The app's one error shape, narrowed to the codes a chat stream can end on.
         */
        ChatErrorResponse: {
            /** Error */
            error: components["schemas"]["ErrorCode"] | components["schemas"]["ChatErrorCode"];
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
            /** Detail */
            detail?: unknown[] | null;
        };
        /**
         * ChatNode
         * @description The graph's nodes, as astream keys their updates.
         * @enum {string}
         */
        ChatNode: "rewrite" | "decompose" | "retrieve" | "assess" | "assess_tools" | "synthesize" | "refuse";
        /**
         * ChatQuery
         * @description The question a caller asks, and the thread it continues — none on a first question,
         *     when the server mints one and returns it on the done frame.
         */
        ChatQuery: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * ChatSource
         * @description One context block as the sources event reports it: what the popover shows and links to.
         */
        ChatSource: {
            /** Marker */
            marker: number;
            /** Name */
            name: string;
            /** Citation */
            citation: string;
            /** Title */
            title: string | null;
            /** Text */
            text: string;
            /** Url */
            url: string;
            /** Site */
            site: string;
        };
        /**
         * ChatStep
         * @description One step as the step event reports it: the result, less the money.
         */
        ChatStep: {
            /** Step */
            step: components["schemas"]["ChatNode"] | components["schemas"]["ToolStep"];
            /** Ms */
            ms: number;
            usage?: components["schemas"]["ChatUsage"] | null;
            /** Model */
            model?: string | null;
            /** @default completed */
            status: components["schemas"]["ChatStepStatus"];
            /** Subject */
            subject?: string | null;
        };
        /**
         * ChatStepStatus
         * @description Where a step is: announced as it starts, then reported again once it has finished.
         * @enum {string}
         */
        ChatStepStatus: "running" | "completed";
        /**
         * ChatUsage
         * @description A step's usage as the wire carries it: the tokens, not what they cost.
         */
        ChatUsage: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /**
         * ChatVote
         * @description The reader's vote on an answer: which way, or None to take it back.
         */
        ChatVote: {
            vote: components["schemas"]["Vote"] | null;
        };
        /**
         * DoneEvent
         * @description The last event of a completed stream, sent once the turn is recorded: where it was.
         */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "done";
            data: components["schemas"]["TurnRecord"];
        };
        /**
         * ErrorCode
         * @description The names core reports its errors under; a capability declares its own beside its errors.
         * @enum {string}
         */
        ErrorCode: "ValidationError" | "HTTPException" | "IntegrityError" | "InternalServerError" | "NotFoundError" | "RateLimitedError" | "TurnstileFailedError" | "UnauthorizedError" | "StorageError" | "ObjectNotFoundError" | "LLMError";
        /**
         * ErrorEvent
         * @description The last event of a failed stream, in the app's one error shape.
         */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "error";
            data: components["schemas"]["ChatErrorResponse"];
        };
        /**
         * ErrorResponse
         * @description The single JSON shape every error response uses, however it is serialized:
         *     the optional fields are left out rather than sent as null.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
            /** Detail */
            detail?: unknown[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            database: components["schemas"]["ServiceStatus"];
            redis: components["schemas"]["ServiceStatus"];
            /** @description Overall status: ok only while every ServiceStatus field reports ok. */
            readonly status: components["schemas"]["HealthStatus"];
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded";
        /**
         * ServiceStatus
         * @enum {string}
         */
        ServiceStatus: "ok" | "error";
        /**
         * SourcesEvent
         * @description Sent once, first: the [n] markers the answer will cite, bound to their chunks.
         */
        SourcesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "sources";
            /** Data */
            data: components["schemas"]["ChatSource"][];
        };
        /**
         * StepEvent
         * @description One step of the path, sent as it starts and again as it finishes.
         */
        StepEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "step";
            data: components["schemas"]["ChatStep"];
        };
        /**
         * TextEvent
         * @description One fragment of the answer's text, as the model streams it — or the whole refusal.
         */
        TextEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "text";
            /** Data */
            data: string;
        };
        /**
         * ToolStep
         * @description The tool calls a path records, prefixed so one column holds both these and the
         *     graph's nodes without either being read for the other.
         * @enum {string}
         */
        ToolStep: "tool_search" | "tool_follow_reference" | "tool_refuse" | "tool_unknown";
        /**
         * TurnRecord
         * @description Where the turn was recorded: the thread it joined, which a follow-up sends back, and
         *     the request it was written as, which a vote names; None when the write failed.
         */
        TurnRecord: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Request Id */
            request_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Vote
         * @description Which way a reader voted on the answer they were given.
         * @enum {string}
         */
        Vote: "up" | "down";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-client-id"?: string | null;
                "cf-turnstile-response"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SourcesEvent"] | components["schemas"]["StepEvent"] | components["schemas"]["TextEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    vote_on_answer_chat__request_id__vote_put: {
        parameters: {
            query?: never;
            header?: {
                "x-client-id"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatVote"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
