/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream a cited answer to the question over SSE: steps, sources, tokens, done with the
         *     thread id; or error.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatNode
         * @description The graph's nodes, as astream keys their updates.
         * @enum {string}
         */
        ChatNode: "rewrite" | "decompose" | "retrieve" | "assess" | "assess_tools" | "synthesize" | "refuse";
        /**
         * ChatQuery
         * @description The question a caller asks, and the thread it continues — none on a first question,
         *     when the server mints one and returns it on the done frame.
         */
        ChatQuery: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * ChatSource
         * @description One context block as the sources event reports it, binding marker to chunk.
         */
        ChatSource: {
            /** Marker */
            marker: number;
            /** Chunk Id */
            chunk_id: number;
            /** Celex */
            celex: string;
            /** Act */
            act: string;
            /** Citation */
            citation: string;
            /** Title */
            title: string | null;
            /** Text */
            text: string;
        };
        /**
         * ChatStepResult
         * @description One step of the path — a graph node, or one tool call a round ran: what it was, how
         *     long it took, and what it spent if it called a model. The shape the ledger persists
         *     per step, and the trace a run is read back from.
         *
         *     status: whether the step has finished. Only the stream announces a running one; every step
         *         the graph appends to the path has returned, so completed is the default.
         *     ms: how long the step took, which a running one has not spent yet and nothing reads.
         *     subject: what the step was about where the step alone does not say — the query a search
         *         ran, the division a follow fetched. Carried to the client, not to the ledger.
         */
        ChatStepResult: {
            /** Step */
            step: components["schemas"]["ChatNode"] | components["schemas"]["ToolStep"];
            /** Ms */
            ms: number;
            usage?: components["schemas"]["TokenUsage"] | null;
            /** @default completed */
            status: components["schemas"]["ChatStepStatus"];
            /** Subject */
            subject?: string | null;
        };
        /**
         * ChatStepStatus
         * @description Where a step is: announced as it starts, then reported again once it has finished.
         * @enum {string}
         */
        ChatStepStatus: "running" | "completed";
        /**
         * ChatThread
         * @description The thread a turn was recorded under, which a follow-up sends back.
         */
        ChatThread: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
        };
        /**
         * DoneEvent
         * @description The last event of a completed stream: the thread the turn belongs to.
         */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "done";
            data: components["schemas"]["ChatThread"];
        };
        /**
         * ErrorEvent
         * @description The last event of a failed stream, in the app's one error shape.
         */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "error";
            data: components["schemas"]["ErrorResponse"];
        };
        /**
         * ErrorResponse
         * @description The single JSON shape every error response uses, however it is serialized:
         *     the optional fields are left out rather than sent as null.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
            /** Detail */
            detail?: unknown[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
            database: components["schemas"]["ServiceStatus"];
            redis: components["schemas"]["ServiceStatus"];
            /** @description Overall status: ok only while every ServiceStatus field reports ok. */
            readonly status: components["schemas"]["HealthStatus"];
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded";
        /**
         * ServiceStatus
         * @enum {string}
         */
        ServiceStatus: "ok" | "error";
        /**
         * SourcesEvent
         * @description Sent once, first: the [n] markers the answer will cite, bound to their chunks.
         */
        SourcesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "sources";
            /** Data */
            data: components["schemas"]["ChatSource"][];
        };
        /**
         * StepEvent
         * @description One step of the path, sent as it starts and again as it finishes.
         */
        StepEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "step";
            data: components["schemas"]["ChatStepResult"];
        };
        /**
         * TextEvent
         * @description One fragment of the answer's text, as the model streams it — or the whole refusal.
         */
        TextEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "text";
            /** Data */
            data: string;
        };
        /**
         * TokenUsage
         * @description The tokens one model call spent, or several calls spent between them.
         */
        TokenUsage: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /**
         * ToolStep
         * @description The tool calls a path records, prefixed so one column holds both these and the
         *     graph's nodes without either being read for the other.
         * @enum {string}
         */
        ToolStep: "tool_search" | "tool_follow_reference" | "tool_refuse" | "tool_unknown";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-client-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SourcesEvent"] | components["schemas"]["StepEvent"] | components["schemas"]["TextEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
